# Generated by Django 5.2.6 on 2025-09-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsRR_DB',
            fields=[
                ('car_model', models.CharField(max_length=1)),
                ('series', models.CharField()),
                ('color', models.CharField(max_length=8)),
                ('price', models.IntegerField(primary_key=True, serialize=False)),
                ('fancy_number', models.IntegerField()),
            ],
        ),
    ]
