# Generated by Django 5.2.6 on 2025-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsrr_db',
            name='car_model',
            field=models.CharField(max_length=10),
        ),
    ]
